# https://ahadsheriff.medium.com/developers-this-is-what-you-should-install-on-your-new-m1-mac-d90cd365c380
format = """
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$gcloud\
$kubernetes\
$username\
$hostname\
$localip\
$docker_context\
$ruby\
$nodejs\
$python\
$terraform\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$container\
$fill\
$time\
$line_break\
$status\
$directory\
$shell\
$line_break\
$character"""

continuation_prompt = " "

[directory]
truncation_symbol = "…/"

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[docker_context]
format = '\[[$symbol$context](bright-cyan)\]'

[gcloud]
format = '\[[$symbol$project](bright-blue)\]'
disabled = false
[gcloud.project_aliases]
indigo-lotus-415 = 'gcp-lotus'
stage-23704 = 'gcp-stage'
apollo-ops = 'gcp-ops'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[git_commit]
tag_disabled = false
only_detached = true

[golang]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol ($context ${namespace})](purple)\]'
symbol = "⛵️"
disabled = false
[kubernetes.context_aliases]
'gke_.*_(.*)' = 'gke-$1'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
format = '\[[$symbol($version)](cyan)\]'
disabled = true

[php]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))](yellow)\]'
disabled = false

[ruby]
format = '\[[$symbol($version)](green)\]'
disabled = false

[rust]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[status]
disabled = false
map_symbol = true

[sudo]
format = '\[$symbol\]'
disabled = false

[terraform]
format = '\[[$symbol$workspace]($style)\]'
disabled = true

[time]
format = '\[[$time]($style)\]'
disabled = false
time_format = "%v %r"

[username]
format = '\[[$user]($style)\]'
show_always = false
disabled = true
