# https://ahadsheriff.medium.com/developers-this-is-what-you-should-install-on-your-new-m1-mac-d90cd365c380
format = """
$kubernetes\
$gcloud\
$fill\
$time\
$line_break\
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$helm\
$nodejs\
$python\
$ruby\
$terraform\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$line_break\
$status\
$container\
$shell\
$character"""

continuation_prompt = "▶▶ "

[directory]
truncation_symbol = "…/"

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[gcloud]
format = '\[[$symbol$project]($style)\]'
disabled = false

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol ($cluster)](green)\]'
symbol = "⛵️"
disabled = false
# detect_folders = ['helm', 'kubernetes']

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[php]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
disabled = false

[ruby]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[rust]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[status]
disabled = false
map_symbol = true

[sudo]
format = '\[$symbol\]'
disabled = false

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'
disabled = false
time_format = "%v %r"

[username]
format = '\[[$user]($style)\]'
show_always = false
disabled = true
